name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
        cache-dependency-path: |
          sub-project/*.gradle*
          sub-project/**/gradle-wrapper.properties

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Setup Minecraft
      uses: mcenv/setup-minecraft@v3
      with:
        version: "1.20.1"
        install: true
        cache: true

    - name: Run Minecraft Server
      run: |
        echo Running Minecraft ${{ steps.setup-minecraft.outputs.version }}.
        echo "eula=true" > eula.txt
        java -jar $MINECRAFT nogui
